services:
  mitigation-manager:
    container_name: resilmesh-sop-mm
    env_file:
      - path: .env
        required: false
    build:
      context: .
    expose:
      - ${PORT:-8002}
    networks:
      - resilmesh_network
