services:
  mitigation-manager:
    container_name: ${CONTAINER_PREFIX}Mitigation-Manager
    env_file:
      - path: .env
        required: false
    build:
      context: .
    expose:
      - ${PORT:-8002}
    networks:
      external:
networks:
  external:
    external: true
    name: ${CONTAINER_NETWORK}
