services:
  mitigation-manager:
    ports:
      - ${MM_PORT:-8002}:${MM_PORT:-8002}
    volumes:
      - ./config.edn:/usr/config.edn:z
      - ./data:/usr/data:z
  nats:
    image: nats:latest
    ports:
      - 8222:8222
      - 4222:4222
    command: -js
    networks:
      external:
